name:                chatbot
version:             0.1.0.0
github:              "omegaGreeNya/chatbot"
license:             BSD3
author:              "Big Man"
maintainer:          "BigMan@FunnyBoys.com"
copyright:           "Big Man Authority"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

default-extensions:
- OverloadedStrings
- DeriveGeneric

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- hspec
- mtl
- text
- QuickCheck

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  echo-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatbot

tests:
  echo-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatbot
